[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "saconvert"
authors = [{name = "Skanda Acharya", email = "skanda.acharya@yahoo.com"}]
dynamic = ["version", "description"]
